import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * The TWA wrapper's manifest is hand-written rather than generated by
 * Bubblewrap, so the components Bubblewrap would emit have to be asserted here
 * instead. This is not theoretical: shipping DelegationService without
 * NotificationPermissionRequestActivity made Notification.requestPermission()
 * hang forever in the installed app, because androidbrowserhelper builds the
 * PendingIntent without checking the component resolves and Chrome then waits
 * on a reply that never arrives.
 */
describe('Android TWA manifest', () => {
  const manifest = readFileSync(
    resolve(process.cwd(), 'android/app/src/main/AndroidManifest.xml'),
    'utf8',
  )

  const declaresActivity = (name: string) =>
    new RegExp(`android:name="com\\.google\\.androidbrowserhelper\\.trusted\\.${name}"`).test(
      manifest,
    )

  it('declares the launcher activity', () => {
    expect(declaresActivity('LauncherActivity')).toBe(true)
  })

  it('declares NotificationPermissionRequestActivity whenever it delegates notifications', () => {
    const delegatesNotifications = declaresActivity('DelegationService')

    if (delegatesNotifications) {
      expect(
        declaresActivity('NotificationPermissionRequestActivity'),
        'DelegationService without NotificationPermissionRequestActivity hangs Notification.requestPermission() forever',
      ).toBe(true)
    }
  })

  it('gives the permission activity a translucent theme', () => {
    // AppTheme is opaque, so the default would flash a full-screen solid colour
    // behind the system permission dialog.
    const block = manifest.match(
      /<activity[^>]*NotificationPermissionRequestActivity[\s\S]*?\/>/,
    )?.[0]

    expect(block).toBeTruthy()
    expect(block).toMatch(/Theme\.Translucent\.NoTitleBar/)
  })

  it('requests the runtime permission Android 13+ needs for delegated notifications', () => {
    expect(manifest).toMatch(/android\.permission\.POST_NOTIFICATIONS/)
  })

  it('declares FocusActivity so a notification tap can focus the app', () => {
    expect(declaresActivity('FocusActivity')).toBe(true)
  })

  it('keeps the delegation service exported with the TWA service intent filter', () => {
    expect(manifest).toMatch(
      /android\.support\.customtabs\.trusted\.TRUSTED_WEB_ACTIVITY_SERVICE/,
    )
  })
})

describe('Android launcher shortcuts', () => {
  const manifest = readFileSync(
    resolve(process.cwd(), 'android/app/src/main/AndroidManifest.xml'),
    'utf8',
  )
  const shortcuts = readFileSync(
    resolve(process.cwd(), 'android/app/src/main/res/xml/shortcuts.xml'),
    'utf8',
  )
  const webManifest = JSON.parse(
    readFileSync(resolve(process.cwd(), 'public/manifest.json'), 'utf8'),
  ) as { shortcuts?: Array<{ url: string }> }

  it('is registered on the launcher activity', () => {
    expect(manifest).toMatch(/android:name="android\.app\.shortcuts"/)
    expect(manifest).toMatch(/android:resource="@xml\/shortcuts"/)
  })

  it('covers the same routes as the PWA manifest shortcuts', () => {
    // Installed-from-browser and installed-from-APK should behave the same.
    for (const shortcut of webManifest.shortcuts ?? []) {
      const route = shortcut.url.split('?')[0]
      expect(shortcuts, `no Android shortcut for ${route}`).toContain(`${route}?`)
    }
  })

  it('targets the launcher activity that the manifest actually declares', () => {
    expect(shortcuts).toContain(
      'com.google.androidbrowserhelper.trusted.LauncherActivity',
    )
    expect(manifest).toContain(
      'com.google.androidbrowserhelper.trusted.LauncherActivity',
    )
  })

  it('does not mark them as conversation shortcuts', () => {
    // android.shortcut.conversation is the People API; using it here would put
    // PushUS in the conversations section of the share sheet.
    expect(shortcuts).not.toContain('android.shortcut.conversation')
  })
})
